### ISSUE TITLE
Soul emoji list | roll timer?

### ISSUE THREAD

**Issue by Kaizuk-O** [Nixeld/MudaeAutoBot#10]
Does the soul emoji list not work? I've set it to claim KakeraO from the soul emoji list but not if its on the non-soulemoji list - any ideas?

*I've also noticed it doesn't roll accurately every hour, so if i start it at xx:00 (my reset time) the next time it rolled was xx:16, then xx:28

**Comment by Kaizuk-O** [comment]
@HANSSS9631 would you happen to have any insight to this by any chance please?

**Comment by HANSSS9631** [comment]
XD currently i do not have any soul characters to test but for the roll timer, it rolls at a random timing between the reset and the nest reset so as to not have all the bots roll at reset. If you wish to make it roll at reset time, you can remove line 428.

**Comment by HANSSS9631** [comment]
Currently the soul emoji list is not fully implemented, u can try adding the `kakeraO` in the `emoji_list` first.

**Comment by Kaizuk-O** [comment]
> XD currently i do not have any soul characters to test but for the roll timer, it rolls at a random timing between the reset and the nest reset so as to not have all the bots roll at reset. If you wish to make it roll at reset time, you can remove line 428.

LEGEND! Thank you! Also, I've just tried to boot it up on a different device and I'm getting the following error when running it, couldnt see anything like it in any other issue before... 
![image](https://github.com/Nixeld/MudaeAutoBot/assets/89078343/d74fefa7-68c8-4e1b-b3be-a3ed7993559c)

I can confirm discum and python 3.11 are installed - you reckon this is a python env issue maybe?

**Comment by Kaizuk-O** [comment]
NVM, i found a trailing comma smh haha

**Comment by Nixeld** [comment]
> Does the soul emoji list not work? I've set it to claim KakeraO from the soul emoji list but not if its on the non-soulemoji list - any ideas?

Soul emoji list should be working now.

> *I've also noticed it doesn't roll accurately every hour, so if i start it at xx:00 (my reset time) the next time it rolled was xx:16, then xx:28

This was done intentionally to make the bot seem more "human".
