### ISSUE TITLE
Question on last minute claim window

### ISSUE THREAD

**Issue by Godstorm7** [Nixeld/MudaeAutoBot#11]
what i need to put here ?
![image](https://github.com/Nixeld/MudaeAutoBot/assets/101065181/b61d4ba3-399a-4f95-8d50-6c7f54ffae2d)

**Comment by HANSSS9631** [comment]
last min claim window is to claim characters at (usually) lower kakera limit that is set in `min_kak` (usually) before the last hour roll( if no characters is claimed within the two hour)

`last_true` - you can set it to true
`last_claim_min` - you can set it to 60
`min_kak_last_min` - set lower than your `min_kak`
