### ISSUE TITLE
Two instances maybe causing an issue?

### ISSUE THREAD

**Issue by Kaizuk-O** [Nixeld/MudaeAutoBot#12]
I've got two instances running on the same server and channel. 

My main one runs absolutely fine, rolls every hour without fail. The second one after about 3 roll resets starts to break and will stop functioning, but weirdly still rolls every hour like 4 or 5 times (out of 23 rolls) and doesn't monitor any kakera or claim anything... 

The settings and .py script are identical to each other so I'm not sure what could be causing this?

**Comment by Nixeld** [comment]
Related to #1
