### ISSUE TITLE
Disabling free kakera reacts

### ISSUE THREAD

**Issue by ghost** [Nixeld/MudaeAutoBot#14]
Removing "kakeraP" from `Settings_Mudae.json` won't disable reacting to them.

**Comment by Nixeld** [comment]
I made it claim kakeraP automatically no matter what was on your emoji_list since it does not require any kakera reaction power.

I will remove the automatic claiming of kakeraP and make it follow whatever is in your list.

**Comment by PwccaCode** [comment]
How to re-enable automatic kakeraP?

**Comment by Nixeld** [comment]
> How to re-enable automatic kakeraP?

Add kakeraP to your kakera list.

**Comment by PwccaCode** [comment]
> > How to re-enable automatic kakeraP?
> 
> Add kakeraP to your kakera list.

Its already added, but still skips as if kakera is on timer

**Comment by HANSSS9631** [comment]
For some reason [28e5ba7](https://github.com/Nixeld/MudaeAutoBot/commit/28e5ba7237443252a182d3cbf8e77842bd7338e4) is gone from the current version so i added it back. @Nixeld (so kakeraP is already inside XD)

KakeraP should be in your `emoji_list` if you want to claim KakeraP.
KakeraP can also be claimed anytime without time restrictions.

**Comment by PwccaCode** [comment]
> For some reason [28e5ba7](https://github.com/Nixeld/MudaeAutoBot/commit/28e5ba7237443252a182d3cbf8e77842bd7338e4) is gone from the current version so i added it back. @Nixeld (so kakeraP is already inside XD)
> 
> KakeraP should be in your `emoji_list` if you want to claim KakeraP. KakeraP can also be claimed anytime without time restrictions.

KakeraP is in my emoji list but after it claims kakeraP it enters the kaker cooldown time and keeps skipping the others

**Comment by Nixeld** [comment]
> KakeraP is in my emoji list but after it claims kakeraP it enters the kaker cooldown time and keeps skipping the others

Try again with the latest version, it should be working now. Just make sure kakeraP is in your kakera list.
