### ISSUE TITLE
does the emoji for "use_emoji" need to be changed

### ISSUE THREAD

**Issue by ghost** [Nixeld/MudaeAutoBot#16]
In `Settings_Mudae.json`, the `use_emoji` setting is set to `<:keqing_love:795077041761288214>`. I was wondering if that has to be changed to a different emoji in order for the bot to react and claim characters

**Comment by ghost** [comment]
Nevermind. It doesn't.

**Comment by Nixeld** [comment]
vivinano made it so that it ignores the emoji in the settings and always use the heart emoji because people are putting the emoji in the wrong format in the settings.
