### ISSUE TITLE
Bot gets this error when ran on an account in multiple servers

### ISSUE THREAD

**Issue by ghost** [Nixeld/MudaeAutoBot#17]
I'm running the bot on my main account instead of an alt, and it gets this. I'm running for a single channel in a single server, but it still breaks.

**Comment by Nixeld** [comment]
Have you tried running `$settings` on that channel? Also verify that the channel and server ids in `Settings_Mudae.json` and `guild.txt` is correct.

**Comment by ghost** [comment]
The settings error is gone but the "please obtain your users settings error" still persists

I just left all my servers to fix it, since I'm only active in one.

**Comment by Nixeld** [comment]
You can ignore that error as long as you have set up your `guild.txt` correctly. The bot will get the servers you are in using `guild.txt` when this error happens so make sure you have set it up properly.

Issue is because Discum is unable to retrieve your guild information.

**Comment by Nixeld** [comment]
Just pushed a fix for it. It should be able to retrieve your user and guild information without using `user.txt` and `guild.txt`
Update your Discum with this command `pip install git+https://github.com/Nixeld/Discord-S.C.U.M.git`
