### ISSUE TITLE
doesnt log and claim

### ISSUE THREAD

**Issue by crazyboypogi** [Nixeld/MudaeAutoBot#18]
it detects people rolling and kakera but doesnt seem detect/log and claim the characters in jsonsettings (min kak/series/namelist)
it does claim kakera though
theres this log at the start after logged in

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000212822C3350>>
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\ASUS\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 812, in on_message
    slashCmds = bot.getGuildSlashCommands(guild_id).json()["application_commands"]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Nixeld** [comment]
You are using the official Discum which has issues due to Discord making changes to their back end changing how slash commands work. 

To fix this:
Uninstall Discum with this command `pip uninstall discum`
Install Discum from this fork `pip install git+https://github.com/Nixeld/Discord-S.C.U.M.git`

**Comment by crazyboypogi** [comment]
thanks for the fix, it fixed it and works fine now although theres some error log
