### ISSUE TITLE
Unable to fetch guilds?

### ISSUE THREAD

**Issue by Legend-Recalls** [Nixeld/MudaeAutoBot#19]
![image](https://github.com/Nixeld/MudaeAutoBot/assets/69719681/edc2e806-e696-4346-8dfb-2ed38efa8b7a)
I had similar issue with official discum, but the issue exists even with Nixeld's fork

**Comment by Nixeld** [comment]
Make sure your guild.txt in the user folder contains the server and channel ids of the channels you want to roll in.
Refer to the example file for how to format it.

**Comment by Nixeld** [comment]
Just pushed a fix for it. It should be able to retrieve your user and guild information without using `user.txt` and `guild.txt`
Update your Discum with this command `pip install git+https://github.com/Nixeld/Discord-S.C.U.M.git`
