### ISSUE TITLE
Last Claim not working?

### ISSUE THREAD

**Issue by Jmlaco22** [Nixeld/MudaeAutoBot#2]
Im slightly worried this is due to some minor mistake on my part but the last claim wouldnt happen even within the time constrains and when the kakera value was above the minimum when testing.

**Comment by Nixeld** [comment]
Could you share you `Settings_Mudae.json` without your token?

**Comment by HANSSS9631** [comment]
May I see the Setting_Mudae.json, the last 4 settings?
