### ISSUE TITLE
Claim Kakera and Last Claim bug

### ISSUE THREAD

**Issue by karma1982** [Nixeld/MudaeAutoBot#20]
Hello, recently, using the bot, I discovered that when it reacts to a Kakera Claim and is in cooldown time, the script recognizes it as if it were a claim and updates the channel time, thus bugging the last_claim

![image](https://github.com/user-attachments/assets/2055db29-6ad1-42bd-9465-30bdf2be46a1)

**Comment by Nixeld** [comment]
Wrong print statement was added there so it is just a display issue. The time displayed is the next time it will claim kakera.

Corrected the print statement in 245a2d2.
