### ISSUE TITLE
Waifu claiming problem

### ISSUE THREAD

**Issue by karma1982** [Nixeld/MudaeAutoBot#21]
Is it normal to be like this? The script is recognizing the 32 min as 10781, is there anything I can do? I've already checked the server settings and everything is fine

![image](https://github.com/user-attachments/assets/2782469b-6dd4-4142-a980-8fa37b7636d2)

**Comment by karma1982** [comment]
The same problem is happening with the last claim min, I set the action to be carried out in the last 10 minutes, but it is happening with around 1 hour left, etc.

![image](https://github.com/user-attachments/assets/21b98c5a-d4b7-4aeb-ad58-c6514d596120)

**Comment by Nixeld** [comment]
Can you go into the channeldata folder and open up the text file for your channel and check that the settings in there matches the one shown in $settings?

Could you also show me what the settings are for 
· Claim reset: every xx min. ($setclaim)
· Exact minute of the reset xx:xx ($setinterval)
· Reset shifted: by +x min. ($shifthour)

**Comment by karma1982** [comment]
Yes, here is the setup.

_ __**Server Settings**__ _
(Server not premium)

· Prefix: **$** ($prefix)
· Lang: **en** ($lang)
· Claim reset: every **180** min. ($setclaim)
· Exact minute of the reset: xx:**00** ($setinterval)
· Reset shifted: by +**0** min. ($shifthour)

**Comment by HANSSS9631** [comment]
Could you help me test the new claim timer/(commit f24ef1c) to see if it is working?

**Comment by karma1982** [comment]
Of course!! I will do several tests and leave the results here! Thank you very much for the answer :D

**Comment by HANSSS9631** [comment]
Sorry the new commit 53dc43d should help I hope.

**Comment by karma1982** [comment]
No need to apologize, thanks for the good work :):
Well, I tested it and it ended up like this, using the update

![image](https://github.com/user-attachments/assets/d00e67fe-118b-42ea-81b7-d2a27b426144)


![image](https://github.com/user-attachments/assets/f918167c-9ca5-4e5f-9d63-bf0bbe43998d)

However, it was on another server, with these settings here, since I ended up deleting my other one.

**Comment by HANSSS9631** [comment]
Try the newer commit :(

**Comment by karma1982** [comment]
> Try the newer commit :(

![image](https://github.com/user-attachments/assets/673a764f-5173-44c0-8646-7ece56fee6a9)

SORRY, I HADN'T SEEN THAT YOU UPDATED AGAIN. Well, I tested it and it worked perfectly, thank you very much!! There was a difference of one minute, counting the seconds, but I don't know if it's the bot's calculation or discord. HOWEVER, THANK YOU VERY MUCH!! I BELIEVE IT WILL WORK

**Comment by karma1982** [comment]
Hello, the solution previously worked, but I ended up noticing that it only worked for a server with the default configuration, in this case:

Prefix: $ ($prefix)
· Lang: en ($lang)
· Claim reset: every 180 min. ($setclaim)
· Exact minute of the reset: xx:44 ($setinterval)
· Reset shifted: by +0 min. ($shifthour).

On my other server that has the configurations:

Prefix: **$** ($prefix)
· Lang: **en** ($lang)
· Claim reset: every **180** min. ($setclaim)
· Exact minute of the reset: xx:**00** ($setinterval)
· Reset shifted: by +**0** min. ($shifthour)

It ended up not working, only being able to detect the minutes and ignoring the hours

![image](https://github.com/user-attachments/assets/14c1ed8e-5d5b-462a-8c23-f34d166e14ae)

**Comment by karma1982** [comment]
The same thing happened on another server, with the settings:

Prefix: $ ($prefix)
· Lang: en ($lang)
· Claim reset: every 180 min. ($setclaim)
· Exact minute of the reset: xx:02 ($setinterval)
· Reset shifted: by +0 min. ($shifthour).

In this one, he recorded 1hr 42 as 2hr 42. 

 By the way, is there a problem if the server settings are in another language? Like PT-BR?

**Comment by Nixeld** [comment]
The bot only supports the english language and will not work properly on other languages. There are currently no plans to add support for other languages.

**Comment by PwccaCode** [comment]
Im having an issue where the bot doesn't claim the kakera prices correctly?

I set it to claim anything above 400, but it will only claim anything thats on my claim list ignoring the kakera value

**Comment by Nixeld** [comment]
> Im having an issue where the bot doesn't claim the kakera prices correctly?
> 
> I set it to claim anything above 400, but it will only claim anything thats on my claim list ignoring the kakera value

Can you share your `Settings_Mudae.json` without your discord token?

**Comment by PwccaCode** [comment]
{
   "token":"token",
   "channel_ids":[
	  1
   ],
   "slash_ids":[
	  channel
   ],
   "slash_guild_ids":[
      17
   ],
   "claim_delay":0,
   "kak_delay":0,
   "use_emoji":"<:keqing_love:795077041761288214>",
   "roll_this":"wa",
   "slash_this":"wa",
   "rolling":"False",
   "slash_rolling":"False",
   "random_rolling":"False",
   "daily_claiming":"False",
   "poke_rolling":"False",
   "series_list":[
   ],
   "name_list":[
      "Rias Gremory",
      "Zero Two",
      "Rem",
      "Rias Gremory",
      "Megumin",
      "Makima",
      "2B",
      "Marin Kitagawa",
      "Power",
      "Satoru Gojo",
      "Madara Uchiha",
      "Yor Forger",
      "Sasuke Uchiha",
      "Sakura Haruno",
      "Kakashi Hatake",
      "Mai Sakurajima",
      "Nezuko Kamado",
      "Mikasa Ackerman",
      "Hange Zoe",
      "Asuna",
      "Saber",
      "Chika Fujiwara",
      "Yumeko Jabami",
      "Emilia",
      "Miku Nakano",
      "Shinobu Kocho",
      "Bongo Cat",
      "Violet Evergarden",
      "Hatsune Miku",
      "Aqua",
      "Akame",
      "Albedo",
      "Levi Ackerman",
      "Himiko Toga",
      "Kaguya Shinomiya",
      "Ram",
      "Kirby",
      "Nino Nakano",
      "Rin Tohsaka",
      "Nami",
      "Akeno Himejima",
      "Hinata Hyuuga",
      "Shiro",
      "Kanna Kamui",
      "Ai Hayasaka",
      "Esdeath",
      "Kurumi Tokisaki",
      "Takanashi Rikka",
      "Raphtalia",
      "Tohru",
      "Uraraka Ochako",
      "Sinon",
      "Neferpitou",
      "Darkness",
      "Shoto Todoroki",
      "Chizuru Ichinose",
      "Nobara Kugisaki",
      "Gawr Gura",
      "Killua Zoldyck",
      "Erza Scarlet",
      "Nico Robin",
      "Asuka Langly Soryu",
      "Chiaki Nanami",
      "Mitsuri Kanroji",
      "Nyan Cat",
      "Katsuki Bakugou",
      "Kurisu Makise",
      "Annie Leonhart",
      "Ryuko Matoi",
      "Eren Jaeger",
      "Hayase Nagatoro",
      "Sasha Braus",
      "Rei Ayanami",
      "Truck-Kun",
      "Taiga Aisaka",
      "Kanao Tsuyuri",
      "Itsuki Nakano",
      "Momo Yaoyorozu",
      "Tanjiro Kamado",
      "Shouko Nishimiya",
      "Osamu Dazai",
      "Kaori Miyazono",
      "Yotsuba Nakano",
      "Tsuyu Asui",
      "Monkey D Luffy",
      "Giyuu Tomioka",
      "Mary Saotome",
      "Touka Kirishima",
      "Krista Lenz",
      "Boa Hancock",
      "Izuku Midoriya",
      "Yukino Yukinoshita",
      "Yuno Gasai",
      "Hestia",
      "Lucy Heartfilia",
      "Kirigiri Kyoko",
      "Shouko Komi",
      "Kyouko Hori",
      "Yuuji Itadori",
      "Erina Nakiri",
      "Junko Enoshima",
      "Alice Synthesis Thirty",
      "Shinobu Oshino",
      "Amber",
      "Ai Ohto",
      "Ken Kaneki",
      "Crona",
      "Echidna",
      "Lucoa",
      "Mitsuha Miyamizu",
      "Zenitsu Agatsuma",
      "Roronoa Zoro",
      "Artoria Pendragon (Alter)",
      "Ichigo",
      "Armin Arlert",
      "Megumi Fushiguro",
      "Rio Futaba",
      "Tsunade",
      "Kyouka Jirou",
      "Naruto",
      "Tatsumaki",
      "Kyoujurou Rengoku",
      "Mirko",
      "Dabi",
      "Misa Amane",
      "Nanika",
      "Nejire Hadou",
      "Nao Tomori",
      "Jean",
      "L",
      "Tobio Kageyama",
      "Inugami Korone",
      "Eri",
      "Sakura Haruno",
      "Ichika Nakano",
      "Fubuki",
      "Tanya Degurechaff",
      "Jibril",
      "Itachi Uchiha",
      "Jolyne Cujoh",
      "Inosuke Hashibira",
      "Sukuna",
      "Lisa",
      "Midnight",
      "Tamaki Kotatsu",
      "Bowsette",
      "Mina Ashido",
      "Sumi Sakurasawa",
      "Kenma Kozume",
      "Jeanne D'Arc",
      "Black Hanekawa",
      "Kurapika",
      "Shouyou Hinata",
      "Venti",
      "Pieck Finger"
   ],
   "emoji_list":[
      "kakeraY",
      "kakeraO",
      "kakeraR",
      "kakeraW",
      "kakeraL"
   ],
   "soulemoji_list":[
      "kakeraO",
      "kakeraR",
      "KakeraW",
      "KakeraL"
   ],
   "min_kak":400,
   "last_true":"False",
   "last_claim_min": 2,
   "min_kak_last_min": 100
}

**Comment by HANSSS9631** [comment]
Ok so how it works is that it will claim your characters in your `name_list` then `series_list` then claim anything above 400 kakera and not claim if you have claimed within the 3 hour window.

Note for @Nixeld:
If the character is in the list and claimed already, it's skip claim for the message and do kakera instead.(intended)

**Comment by Nixeld** [comment]
> Im having an issue where the bot doesn't claim the kakera prices correctly?
> 
> I set it to claim anything above 400, but it will only claim anything thats on my claim list ignoring the kakera value

The bot will priortise claiming characters in your claim list first then claim any characters that are above 400 kakera. So if a character that is in your claim list spawn, it will claim that and ignore any characters that are above 400 kakera.

Since you have quite a number of characters in your claim list, I am guessing that there are a lot claim list character spawning so it will claim those instead of claiming characters above 400 kakera.

If this is not the behaviour you are observing, please send some screenshots of your discord channel showing the problem.
