### ISSUE TITLE
Time displaying wrong

### ISSUE THREAD

**Issue by NineLEL** [Nixeld/MudaeAutoBot#22]
There is a significant mismatch between the time shown in the console and the time displayed by the Mudae bot. The console time appears incorrect, often showing a difference of more than 10 minutes compared to what the Mudae bot displays.

It's supposed to be 30 minutes but shown as 39 minutes (from my calculations)
![image](https://github.com/user-attachments/assets/7b1afc09-7bb6-4633-8a1b-83c7cf4990d3)
![image](https://github.com/user-attachments/assets/68fe1a68-2c0e-4e06-9708-65cc294093fa)

`_ __**Server Settings**__ _
(Server not premium)

· Prefix: **$** ($prefix)
· Lang: **en** ($lang)
· Claim reset: every **180** min. ($setclaim)
· Exact minute of the reset: xx:**59** ($setinterval)
· Reset shifted: by +**0** min. ($shifthour)
· Rolls per hour: **10** ($setrolls)
· Time before the claim reaction expires: **45** sec. ($settimer)
· Spawn rarity multiplicator for already claimed characters: **2** ($setrare)
· % kakera bonus: **+0** ($setkakerabonus)
· Game mode: **1** ($gamemode)
· This channel instance: **1** ($channelinstance)
· Slash commands: enabled ($toggleslash)

· Ranking: enabled ($toggleclaimrank/$togglelikerank)
· Ranks displayed during rolls: **disabled** ($togglerolls)
· Hentai series: enabled ($togglehentai)
· Disturbing imagery series: enabled ($toggledisturbing)
· Child characters: enabled ($togglechildtag)
· Rolls sniping: 0 ($togglesnipe)
· Kakera sniping: 0 ($togglekakerasnipe)
· Limit of characters per harem: **10000** ($haremlimit)
· Reacts: ****for all your rolls**** ($togglereact)
· Custom reactions: no ($claimreact)
· Kakera reactions more recognizable: no ($kakerareact switchset)

· Kakera trading: enabled ($togglekakeratrade)
· Kakera calculation: claim and like ranks (and number of claimed characters) ($togglekakeraclaim/$togglekakeralike)
· Kakera value displayed during rolls: enabled ($togglekakerarolls)
· $kakeraloot wishprotect: enabled ($togglewishprotect)`

**Comment by NineLEL** [comment]
Or maybe my config is wrong, I'm not sure.

**Comment by HANSSS9631** [comment]
Oh this is an intended feature of randomly rolling with the hour of reset.
If you want to roll exactly on reset, you can remove line 423.
If there is nothing wrong you can close this issue

**Comment by NineLEL** [comment]
I want it to do like /tu and then 5-10 seconds later it roll

**Comment by HANSSS9631** [comment]
You have to add it on your own. I give you directions.

line 811 you have to add another condition for /tu and get the slash command
line 817 add the /tu in to the args
line 351 add the /tu in the args
then add the slash command somewhere inside line 369
How to add slash command: Line 380
How to make it stop for 5-10 seconds: time.sleep()
Maybe Line 834 has something as well

**Comment by NineLEL** [comment]
I know discord.js but not this so thank you so much!
