### ISSUE TITLE
Logging fails NOT RUNNING

### ISSUE THREAD

**Issue by nasseralharbi12** [Nixeld/MudaeAutoBot#23]
![Desktop Screenshot 2024 09 24 - 21 27 17 12](https://github.com/user-attachments/assets/73b68d5e-9b51-4bc1-8382-65f82dcaa13d)

I did everything but when I tried to run it that what happened 
I checked everything and all good

**Comment by PwccaCode** [comment]
channel id is incorrect or guild id is incorrect.

channel id and slash channel id should be the same < the id of the channel you are using mudae in
slash guild id = id of the discord server the channel above resides

**Comment by HANSSS9631** [comment]
Did u install our version of discum?

Read the README.md

**Comment by nasseralharbi12** [comment]
It works thanks !! I tried to reinstall discum and changed the id guild i didnt know it was the server id but it works now

**Comment by nasseralharbi12** [comment]
I have a tiny question i run the bot but how can I time the claim with the reset ? And it seems like when the rolls finish he typed next roll in 4500s but the rolls will reset in less than 4500

**Comment by HANSSS9631** [comment]
Put `random_rolling` to False

**Comment by nasseralharbi12** [comment]
Great the rolls fixed but what about the claim how can i set it to the exact claim reset

**Comment by HANSSS9631** [comment]
??? it is automatic....
If u want you can change the channeldata folder and change the exact minute and reset shifted manually for each channel

**Comment by PwccaCode** [comment]
im still having an issue with the bot sometimes not even seeying a high kakera card in chat. its like it doesn't even register it in log
