### ISSUE TITLE
Bot Dont run anymore

### ISSUE THREAD

**Issue by nasseralharbi12** [Nixeld/MudaeAutoBot#25]
Do anyone know the problem ? The bot started to reconnect over and over and not working idk why ?

**Comment by HANSSS9631** [comment]
Can you screenshot the errors and provide your configuration?

**Comment by nasseralharbi12** [comment]
![Desktop Screenshot 2024 10 18 - 12 05 49 100](https://github.com/user-attachments/assets/c4b25c53-5783-4a19-b453-0fdfa45c6e67)
![Desktop Screenshot 2024 10 18 - 12 08 35 93](https://github.com/user-attachments/assets/1f78a5ab-acde-40f5-872c-228f42e52044)


There is no error when I try to run AutoRecconect It just keep looping 
I tried to run MudaeAutoBot doesn't give me any errors

**Comment by nasseralharbi12** [comment]
I solve the problem
