### ISSUE TITLE
Unable to slash roll

### ISSUE THREAD

**Issue by Hyra666** [Nixeld/MudaeAutoBot#4]
Hello there, could you pls help me solve this problem: 

Logged in
Reading from File for channel 1183807954865115147
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001B699EF69D0>>
Traceback (most recent call last):
  File "C:\Users\Nisha\AppData\Roaming\Python\Python312\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Nisha\Downloads\MudaeAutoBot-main\MudaeAutoBot.py", line 808, in on_message
    s = SlashCommander(slashCmds, application_id=str(mudae))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nisha\AppData\Roaming\Python\Python312\site-packages\discum\utils\slash.py", line 9, in __init__
    elif type(commands) in (list, tuple) and isinstance(commands[0], dict):
                                                        ~~~~~~~~^^^
IndexError: list index out of range.


Im getting this error when i launch the py file and i configurated everything perfectly.

**Comment by Nixeld** [comment]
Discord made some changes on their end and discum is not able to get the application commands anymore. 
Other discord API wrappers are also having the same problem. https://github.com/dolfies/discord.py-self/issues/647

I doubt discum is getting a fix for it as it has not been updated for over 2 years now so just use normal rolling instead of slash rolling. The error will still appear but it should work normally.

**Comment by Hyra666** [comment]
I mean it was working well for 2 days but suddenly when I launched the bot yesterday it showed me this error. Anyway thanks for letting me know that slash won't work I'll use normal rolls for the time being. 👍

Also could you please add me on discord (username: hyra666) so I can contact you faster. I wanted to discuss about something

**Comment by Nixeld** [comment]
If you are experiencing this issue. 
Uninstall discum with `pip uninstall discum`
and install discum from my fork with `pip install git+https://github.com/Nixeld/Discord-S.C.U.M.git`

**Comment by Hyra666** [comment]
its still not working tho

**Comment by Nixeld** [comment]
Make sure you also have the latest version of MudaeAutoBot

**Comment by Hyra666** [comment]
Could you indicate me which one is it please? I think i have the lastest version but idk its not working, i just tried it. I assume that the script wont click on buttons too now? Like the reactions under wished characters since slash also isnt working?

**Comment by Nixeld** [comment]
> Could you indicate me which one is it please? I think i have the lastest version but idk its not working, i just tried it. I assume that the script wont click on buttons too now? Like the reactions under wished characters since slash also isnt working?

https://github.com/Nixeld/MudaeAutoBot/blob/main/MudaeAutoBot.py
This file, it was updated yesterday. Clicking on buttons still work as usual.

**Comment by Hyra666** [comment]
Ok so after reinstalling discum and using the latest version of the script slashes are working but could you add me on discord (hyra666) i have other questions. Its way faster and easier to communicate there
