### ISSUE TITLE
Claim/react delay

### ISSUE THREAD

**Issue by Hyra666** [Nixeld/MudaeAutoBot#5]
Hello, sorry if i opened another issue but, i wanted to ask if we can make the bot react faster because it failed to claim 4 of my wishes (ppl on the server reacted faster than the bot even tho i configured "claim delay=0".

**Comment by HANSSS9631** [comment]
The only delay claim has is the server claim delay and this
![image](https://github.com/Nixeld/MudaeAutoBot/assets/97141634/6dfb7be5-80d4-4c05-b1ea-225db8d9b731)
you can try to remove line 439.
Even so it would take about 3 seconds to claim after the character comes out. The other factors that affect the time are discum, internet speed and CPU(most likely not).
