### ISSUE TITLE
Stops functioning properly after some time

### ISSUE THREAD

**Issue by Hyra666** [Nixeld/MudaeAutoBot#7]
Hey there? I was wondering why the bot stops functioning after some time. Like it only do half of the rolls in my case it rolls 6 rolls only when i have 14 in total. Also it stops logging the characters rolled or wishes spawned and kakera reactions in the console. Could you help me w that. One more thing is that the bot takes a while to react to my wished characters ( it clicks the button way after someone has already reacted even though i have claim delay set to 0.2 ) or characters the list in the config file.

**Comment by HANSSS9631** [comment]
Read #1 and #5
