### ISSUE TITLE
[ISSUE] Missing `EMAIL` metadata in Nixeld/Discord-S.C.U.M causes error upon installation

### ISSUE THREAD

**Issue by tedzify** [Nixeld/MudaeAutoBot#8]
Fix
---
Create a new line and add `EMAIL = 'anyemail@email.com'` below [Nixeld/Discord-S.C.U.M/blob/33eb817/setup.py#L14](https://github.com/Nixeld/Discord-S.C.U.M/blob/33eb817874a13b374b4b66618597958974046753/setup.py#L14)

**Comment by HANSSS9631** [comment]
Thanks, It's fixed.
